- name: setup mongodb server
  hosts: mongodb
  become: yes
  roles:
  - mongodb

# ansible roles? --> ansible roles is a proper directory structure of creating playbooks, maintaining the playbooks and reusing the playbooks. roles will have tasks, files, vars, defaults, handlers, templates. By default roles will try to load main.yaml in each directory